# For a quick start check out our HTTP Requests collection (Tools|HTTP Client|Open HTTP Requests Collection).
#
# Following HTTP Request Live Templates are available:
# * 'gtrp' and 'gtr' create a GET request with or without query parameters;
# * 'ptr' and 'ptrp' create a POST request with a simple or parameter-like body;
# * 'mptr' and 'fptr' create a POST request to submit a form with a text or file field (multipart/form-data);
POST http://localhost:8080/api/team/list?teamcode=T&teamname=R
Cookie: _ga=GA1.1.5520731.1546405316; JSESSIONID=9683068A9D1E7E479F9AFDB0ECEAF586
X-CSRF-TOKEN: 3a3a4f9d-c592-4855-a544-da0deb2196bf





//Content-Type: application/json

//{"teamcode":"T","teamname":"노"}





###

###
###
###