# For a quick start check out our HTTP Requests collection (Tools|HTTP Client|Open HTTP Requests Collection).
#
# Following HTTP Request Live Templates are available:
# * 'gtrp' and 'gtr' create a GET request with or without query parameters;
# * 'ptr' and 'ptrp' create a POST request with a simple or parameter-like body;
# * 'mptr' and 'fptr' create a POST request to submit a form with a text or file field (multipart/form-data);

POST https://dev.broadwave.co.kr/api/team/list?teamcode=T&teamname=R
Cookie: _ga=GA1.3.438373131.1543197813; _gid=GA1.3.1458724510.1554777394; JSESSIONID=252DC33EF439D972DA5A01B30E02C4D4
X-CSRF-TOKEN: 330717fd-c370-40e4-8a48-9d0a21549480

###